---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: rockylinux/rockylinux:9-ubi
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        lmod_modulepaths_path: /etc/lmod/modulepath
        lmod_extra_env_vars:
          LMOD_PAGER: /bin/less
        lmod_default_modules:
          - lmod
verifier:
  name: ansible
