---
# This is an example playbook to execute Ansible tests.

- name: Create test user
  hosts: all
  gather_facts: false
  tasks:
    - name: "Create testusers group"
      ansible.builtin.group:
        name: testusers
        state: present
    - name: "Create testuser"
      ansible.builtin.user:
        name: testuser
        group: testusers
        create_home: true
        shell: /bin/bash
    - name: Install sudo
      ansible.builtin.package:
        name: sudo
        state: present

- name: Verify
  hosts: all
  gather_facts: false
  become: true
  become_user: testuser
  tasks:
    - name: Check that module lmod is loaded
      ansible.builtin.command:
        cmd: "bash -l -c 'module --redirect -t list'"
      register: lmod_load_cmd
      changed_when: lmod_load_cmd.rc != 0
    - name: Print output of module listing
      ansible.builtin.debug:
        msg: "{{ lmod_load_cmd.stdout }}"
    - name: Verify that module lmod is loaded by default
      ansible.builtin.assert:
        that: "lmod_load_cmd.stdout == 'lmod'"
